name: Publish to npm

on:
  schedule:
    - cron: "0 0,8,16 * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Check for changes in dist
        id: git-check
        run: |
          git fetch origin main
          if git diff --quiet origin/main -- dist; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Bump version smartly
        if: steps.git-check.outputs.changed == 'true'
        run: |
          DAY=$(date +'%d')
          if [ "$DAY" = "01" ]; then
            npm version minor --no-git-tag-version --force
          else
            npm version patch --no-git-tag-version --force
          fi

      - name: Publish package
        if: steps.git-check.outputs.changed == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
